### ISSUE TITLE
Plone 6 (Frontend)

### ISSUE THREAD

**Issue by tisto** [plone/plone.volto#1]
# ToDo First Release

* [x] Green gh actions (https://github.com/plone/plone.volto/actions/runs/1225997194)
* [x] Refactor kitconcept.volto into plone.volto (https://github.com/plone/plone.volto/pull/2)
* [x] Apply best practices GH actions (https://github.com/plone/plone.volto/pull/3)
* [x] Update README to reflect this is a community package now (https://github.com/plone/plone.volto/pull/4)
* [x] Pass the package to @plone/volto-team for approval
* [x] Pass the package to @plone/framework-team for approval
* [x] Figure out a way to properly do CI with plone.volto, plone.restapi and Volto
* [x] Document the Plone 6 frontend stack
* [x] Make a first release 3.0.0a1

-> https://pypi.org/project/plone.volto/3.0.0a1/#a1-2021-09-25

# ToDo Pre-Plone 6

* [x] Test plone.volto against Plone 6 (first alpha) (https://github.com/plone/plone.volto/pull/10)
* [x] Replace kitconcept.volto with plone.volto in the Volto repo (https://github.com/plone/volto/pull/2698)
* [x] Make kitconcept.volto depend on plone.volto (https://github.com/kitconcept/kitconcept.volto/pull/41)
* [x] Make a first release of kitconcept.volto 3.0.0.alpha.0 that depends on plone.volto

-> https://pypi.org/project/kitconcept.volto/3.0.0a1/

## 4.0.0

* [x] Use slate as text block default (https://github.com/plone/plone.volto/pull/42)
* [x] Remove dependency on collective.folderishtypes (https://github.com/plone/plone.volto/pull/36)
* [x] Add towncrier configuration (ToDo)
* [x] Add volto.blocks to News Item and Event (https://github.com/plone/plone.volto/pull/35)
* [x] Make Volto compatible with DX site root (https://github.com/plone/plone.restapi/pull/1220)
* [x] Improvements on testing isolation (https://github.com/plone/plone.volto/pull/39)
* [x] Cleanup and GS improvements (https://github.com/plone/plone.volto/pull/43)

## Later

* [ ] Upgrade step from kitconcept.volto to plone.volto

# Plone Conference Fanzone Sorrento Discussions

* [ ] Define release management for Plone 6 frontend stack
* [ ] Commitment to a fixed released schedule once Plone 6 is out (@plone/volto-team and @plone/release-team)

# Volto

* [x] Volto 14 (Locking, Seamless Mode, ...)
* [x] Slate Editor Integration

# Plone REST API 9

https://github.com/plone/plone.restapi/milestone/20

* [ ] Move blocks behavior from plone.restapi (https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/behaviors.py#L21) to plone.volto
* [ ] Move translations to plone.app.locales (https://github.com/plone/plone.restapi/issues/841)
* [ ] Remove deprecated tiles endpoint (https://github.com/plone/plone.restapi/issues/674)
* [ ] Remove deprecated lock endpoint functionality (https://github.com/plone/plone.restapi/issues/1181)

**Comment by tisto** [comment]
FWT meeting notes:

* +1 from the FWT to get rid of c.folderishtypes
* +1 from the FWT to keep folderish document in the plone.volto package and not have folderish types for Plone Classic
