### ISSUE TITLE
Prepare plone.volto to Plone 6.1

### ISSUE THREAD

**Issue by ericof** [plone/plone.volto#155]
# Tasks

- [x] Drop support for Plone 5.2
- [x] Drop support for Plone 6.0
- [x] Use plone/meta
- [x] Move tests to pytest
- [x] [Add `default` distribution](https://github.com/plone/plone.distribution/issues/80)

**Comment by stevepiercy** [comment]
Two more for your consideration:

- [ ] Update `README.md` with current information.
- [ ] Perhaps move some of the `README.md` updates into the open PR https://github.com/plone/documentation/pull/1671/

I'm happy to help with both of these, because I am neck-deep in making it easier for developers to contribute to Plone core through our documentation.
